"""Regenerate the AdjustQ_check baseline CSVs from the current Python build.

The baselines in ``nwsrfs_py/nwsrfs_py/data/Adjustq_check/`` were generated by
an earlier ("rfcmodels-era") build and were never refreshed after the
FP-contraction fix, so they drift from what the current Fortran build
produces. This script regenerates both baselines from ``AdjustQ.load_example``
so they reflect the current build.

Writes:
    nwsrfs_py/nwsrfs_py/data/Adjustq_check/NRKW1_w_sim.csv
    nwsrfs_py/nwsrfs_py/data/Adjustq_check/NRKW1_wout_sim.csv

Schema is preserved exactly: header ``datetime_local_tz,Inst_Streamflow_cfs``,
naive local timestamps formatted as ``YYYY-MM-DD HH:MM:SS``. Only the flow
values are expected to change; timestamps and row counts are governed by the
bundled NRKW1 observation data and should not change.

Run via `pixi run 'python dev/regenerate-adjustq-baselines.py'` (after
`pixi run install-py`).
"""

from __future__ import annotations

import os
import sys

from nwsrfs_py import utils
from nwsrfs_py.adjustq import AdjustQ

OUTPUT_FILES = {
    True: "NRKW1_w_sim.csv",
    False: "NRKW1_wout_sim.csv",
}


def regenerate(sim: bool, example_dir: str) -> str:
    """Run AdjustQ.load_example(sim=...) and write its result as a baseline CSV."""
    print(f"Running AdjustQ.load_example(sim={sim}) ...")
    adjq = AdjustQ.load_example(sim=sim)

    series = adjq.adjustq.rename("Inst_Streamflow_cfs")
    series.index = series.index.rename("datetime_local_tz")

    out_path = os.path.join(example_dir, OUTPUT_FILES[sim])
    series.to_csv(out_path, header=True, index=True)
    print(f"Wrote {len(series)} rows to {out_path}")
    return out_path


def main() -> int:
    with utils._get_example_dir("Adjustq_check") as example_dir:
        for sim in (True, False):
            regenerate(sim, example_dir)
    return 0


if __name__ == "__main__":
    sys.exit(main())
