[build-system]
requires = ["meson-python", "meson>=1.1.0", "numpy", "ninja"] # What packages are needed to build this project
build-backend = "mesonpy"  # The tool that runs the build process (here, setuptools)

[project]
name = "nwsrfspy"                                              # The name of the installable package (used by pip)
version = "1.0.3"                                              # Semantic version (major.minor.patch)
description = "Python tools for NWS RFC NWSRFS modeling with FORTRAN source code integration" # Short description for metadata         
authors = [
    { name = "Geoffrey Walters PE", email = "geoffrey.walters@noaa.gov" },
    { name = "Cameron Bracken", email = "cameron.bracken@pnnl.gov" },
] # Package authors
maintainers = [
    { name = "Geoffrey Walters PE", email = "geoffrey.walters@noaa.gov" },
    { name = "Cameron Bracken", email = "cameron.bracken@pnnl.gov" },
] # Current package maintainers
readme = "README.md"                                           # File to use for long description on PyP
license = { file = "LICENSE" }                                 # file with license information
requires-python = ">=3.10"                                      # Minimum required Python version
dependencies = [                                               # Runtime dependencies installed with the package
    "numpy",
    "pandas",
    "scipy"
]

keywords = [
    "hydrology",
    "nwsrfs",
    "conceptual-modeling",
    "operational-forecasting",
    "operations",
    "noaa",
    "national-weather-service",
    "nws",
    "river-forecast-centers",
    "rfc"
]

classifiers = [
    "Development Status :: 3 - Alpha",                  # Change to 4 - Beta or 5 - Production/Stable later
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Hydrology",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Fortran",
    "License :: OSI Approved :: Apache Software License",         
    "Operating System :: POSIX :: Linux",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: Microsoft :: Windows",
]

[project.optional-dependencies]
docs = [
    "sphinx",
    "sphinx-autodoc-typehints",
    "sphinx-rtd-theme"
]
test = ["pytest"]
